/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface Reservation {
  'id' : bigint,
  'date' : string,
  'name' : string,
  'time' : string,
  'notes' : string,
  'timestamp' : bigint,
  'phone' : string,
  'guests' : bigint,
}
export interface _SERVICE {
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllReservations' : ActorMethod<[], Array<Reservation>>,
  'getContactSubmission' : ActorMethod<[bigint], ContactSubmission>,
  'getReservation' : ActorMethod<[bigint], Reservation>,
  'makeReservation' : ActorMethod<
    [string, string, string, string, bigint, string],
    { 'id' : bigint, 'timestamp' : bigint }
  >,
  'submitContact' : ActorMethod<
    [string, string, string, string],
    { 'id' : bigint, 'timestamp' : bigint }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];