/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const Reservation = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'guests' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getContactSubmission' : IDL.Func([IDL.Nat], [ContactSubmission], ['query']),
  'getReservation' : IDL.Func([IDL.Nat], [Reservation], ['query']),
  'makeReservation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : IDL.Int })],
      [],
    ),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : IDL.Int })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const Reservation = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'guests' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getContactSubmission' : IDL.Func(
        [IDL.Nat],
        [ContactSubmission],
        ['query'],
      ),
    'getReservation' : IDL.Func([IDL.Nat], [Reservation], ['query']),
    'makeReservation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : IDL.Int })],
        [],
      ),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : IDL.Int })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };